def getCCAA(provincia):
	# TODO lowercase and probably this should be in a class
	dict = {
		'Álava' : 'País Vasco', 'Araba/Álava' : 'País Vasco',
		'Albacete' : 'Castilla-La Mancha',
		'Alicante' : 'Comunidad Valenciana',
		'Almería' : 'Andalucía',
		'Asturias' : 'Principado de Asturias',
		'Ávila' : 'Castilla y León',
		'Badajoz' : 'Extremadura',
		'Barcelona' : 'Cataluña',
		'Burgos' : 'Castilla y León',
		'Cáceres' : 'Extremadura',
		'Cádiz' : 'Andalucía',
		'Cantabria' : 'Cantabria',
		'Castellón' : 'Comunidad Valenciana',
		'Ciudad Real' : 'Castilla-La Mancha',
		'Córdoba' : 'Andalucía',
		'La Coruña' : 'Galicia',
		'Cuenca' : 'Castilla-La Mancha',
		'Gerona' : 'Cataluña',
		'Granada' : 'Andalucía',
		'Guadalajara' : 'Castilla-La Mancha',
		'Guipúzcoa' : 'País Vasco',
		'Huelva' : 'Andalucía',
		'Huesca' : 'Aragón',
		'Baleares' : 'Islas Baleares',
		'Jaén' : 'Andalucía',
		'León' : 'Castilla y León',
		'Lérida' : 'Cataluña',
		'Lugo' : 'Galicia',
		'Madrid' : 'Comunidad de Madrid',
		'Málaga' : 'Andalucía',
		'Murcia' : 'Región de Murcia',
		'Navarra' : 'Navarra',
		'Orense' : 'Galicia',
		'Palencia' : 'Castilla y León',
		'Las Palmas' : 'Canarias',
		'Pontevedra' : 'Galicia',
		'La Rioja' : 'La Rioja',
		'Salamanca' : 'Castilla y León',
		'Segovia' : 'Castilla y León',
		'Sevilla' : 'Andalucía',
		'Soria' : 'Castilla y León',
		'Tarragona' : 'Cataluña',
		'Santa Cruz de Tenerife' : 'Canarias',
		'Teruel' : 'Aragón',
		'Toledo' : 'Castilla-La Mancha',
		'Valencia' : 'Comunidad Valenciana',
		'Valladolid' : 'Castilla y León',
		'Vizcaya' : 'País Vasco',
		'Zamora' : 'Castilla y León',
		'Zaragoza' : 'Aragón'
	}
	return dict[provincia]
