def getCCAA(provincia):
	# TODO lowercase and probably this should be in a class
	dict = {
		'álava' : 'país vasco', 'araba/álava' : 'país vasco',
		'albacete' : 'castilla-la mancha',
		'alicante' : 'comunidad valenciana',
		'almería' : 'andalucía',
		'asturias' : 'principado de asturias',
		'ávila' : 'castilla y león',
		'badajoz' : 'extremadura',
		'barcelona' : 'cataluña',
		'burgos' : 'castilla y león',
		'cáceres' : 'extremadura',
		'cádiz' : 'andalucía',
		'cantabria' : 'cantabria',
		'castellón' : 'comunidad valenciana',
		'ciudad real' : 'castilla-la mancha',
		'córdoba' : 'andalucía',
		'la coruña' : 'galicia',
		'cuenca' : 'castilla-la mancha',
		'gerona' : 'cataluña',
		'granada' : 'andalucía',
		'guadalajara' : 'castilla-la mancha',
		'guipúzcoa' : 'país vasco',
		'huelva' : 'andalucía',
		'huesca' : 'aragón',
		'baleares' : 'islas baleares',
		'jaén' : 'andalucía',
		'león' : 'castilla y león',
		'lérida' : 'cataluña',
		'lugo' : 'galicia',
		'madrid' : 'comunidad de madrid',
		'málaga' : 'andalucía',
		'murcia' : 'región de murcia',
		'navarra' : 'navarra',
		'orense' : 'galicia',
		'palencia' : 'castilla y león',
		'las palmas' : 'canarias',
		'pontevedra' : 'galicia',
		'la rioja' : 'la rioja',
		'salamanca' : 'castilla y león',
		'segovia' : 'castilla y león',
		'sevilla' : 'andalucía',
		'soria' : 'castilla y león',
		'tarragona' : 'cataluña',
		'santa cruz de tenerife' : 'canarias',
		'teruel' : 'aragón',
		'toledo' : 'castilla-la mancha',
		'valencia' : 'comunidad valenciana',
		'valladolid' : 'castilla y león',
		'vizcaya' : 'país vasco',
		'zamora' : 'castilla y león',
		'zaragoza' : 'aragón'
	}
	return dict[provincia.lower()]
